/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as ModulosRouteImport } from './routes/modulos'
import { Route as MapasRouteImport } from './routes/mapas'
import { Route as FazendasRouteImport } from './routes/fazendas'
import { Route as IndexRouteImport } from './routes/index'

const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulosRoute = ModulosRouteImport.update({
  id: '/modulos',
  path: '/modulos',
  getParentRoute: () => rootRouteImport,
} as any)
const MapasRoute = MapasRouteImport.update({
  id: '/mapas',
  path: '/mapas',
  getParentRoute: () => rootRouteImport,
} as any)
const FazendasRoute = FazendasRouteImport.update({
  id: '/fazendas',
  path: '/fazendas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fazendas': typeof FazendasRoute
  '/mapas': typeof MapasRoute
  '/modulos': typeof ModulosRoute
  '/relatorios': typeof RelatoriosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fazendas': typeof FazendasRoute
  '/mapas': typeof MapasRoute
  '/modulos': typeof ModulosRoute
  '/relatorios': typeof RelatoriosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fazendas': typeof FazendasRoute
  '/mapas': typeof MapasRoute
  '/modulos': typeof ModulosRoute
  '/relatorios': typeof RelatoriosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/fazendas' | '/mapas' | '/modulos' | '/relatorios'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/fazendas' | '/mapas' | '/modulos' | '/relatorios'
  id: '__root__' | '/' | '/fazendas' | '/mapas' | '/modulos' | '/relatorios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FazendasRoute: typeof FazendasRoute
  MapasRoute: typeof MapasRoute
  ModulosRoute: typeof ModulosRoute
  RelatoriosRoute: typeof RelatoriosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modulos': {
      id: '/modulos'
      path: '/modulos'
      fullPath: '/modulos'
      preLoaderRoute: typeof ModulosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapas': {
      id: '/mapas'
      path: '/mapas'
      fullPath: '/mapas'
      preLoaderRoute: typeof MapasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fazendas': {
      id: '/fazendas'
      path: '/fazendas'
      fullPath: '/fazendas'
      preLoaderRoute: typeof FazendasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FazendasRoute: FazendasRoute,
  MapasRoute: MapasRoute,
  ModulosRoute: ModulosRoute,
  RelatoriosRoute: RelatoriosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
